### ISSUE TITLE
no release, can't go install https://github.com/samxsmith/goboe

### ISSUE THREAD

**Issue by j2l** [samxsmith/goboe#1]
Hi, it's missing a release :)

**Comment by samxsmith** [comment]
Hi @j2l 
Thanks for your comment.
I hadn't created a release because I wasn't yet sure what I'd be able to support going forward.

I've now created a v1 release with the feature set I'm confident in properly supporting.
Hope this helps!

**Comment by j2l** [comment]
Good!
